# Generated by Django 3.1.2 on 2020-11-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0002_auto_20201016_0702"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
