# Generated by Django 3.1.2 on 2020-11-05 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='assigment',
            new_name='assignment',
        ),
    ]
