# Generated by Django 3.1.2 on 2020-12-24 11:07

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='attached_file',
            field=models.FileField(storage=core.storage.OverwriteFileSystemStorage, upload_to='labs/%Y/%m/%d/'),
        ),
    ]
